travis:
  secure:
    BINSTAR_TOKEN: B7OdZ/YiNLZsPY8Uaf2EfQWVzr+OIbBvdf6xyqBrbsquk35Ke9YFKRvMva+LbEycVvg2WDLXKn9uwOuwq/Hx3LkH6MD2W2WkTqqLyXdCuUfxQPQHvN9OUxyVxH9UkCjZjoDY2X6j9Mat1ZpPTCGLlsnNMLA21p8EhZ0HEe8JlnuzyLn86R/fNKtcxWWCV1wW7N+Z6oip/MjSO4GMXiQdPSU9gcczwoa8m+xyM9d4OKNPnJZgpnDzEfRlsjiHgatP2cS+DMnNp6IEPeEIS6p06wHTAfoRW0VJOLff8q5HsRcu8q650c8ol9TRrbF60Fk7n4Y/9z+uHI8r5ShPGLymRerGfxBdvLQPwFnVxsQ9DrXeemW0p7Ny31f1h1BP9U5pYk8ANJf2ros3rTvKBufIGH2s5TbW6OHbPd6I3pZ8MH62ev7x4AmSBi6ii2BjyYqq8DY7wKE4Qan8L16oLp1k0F2iIbMd10HiInmr1pH9h+4Ll+xnS8zsokJQ7RapMxyZifXnioSFnDhVT9OJSxn/X5JVWvBZgTPY6QZ2i7J9EU0KEljQkziQpMrTRjwUrrMJi7YUZtyWZbV4GMvJ2GCG9UMuh8tMbqY/7ofN2yurWfHoSfxy8bf/WoPIYwWmVqvu4mjfEZeSLUv1AolQ5DdSEPjF1yversvyvC9x9GXSQmc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
